### ISSUE TITLE
the wins function doesnt work wat shud i call value or the var

### ISSUE THREAD

**Issue by pareshsolanki29** [pareshsolanki29/pareshsolanki29.github.io#5]
console.log("tictacktoe linked");

var counter = 0

var letPlay = $("#start").click(function(){
$(".welcome").fadeOut(1000)
 // $("#board").toggle()
});
var boxes = ["tl1","tl2","tl3","ml","ml2","ml3","bl1","bl2","bl3"];
var box1;
var box2;
var box3;
var box4;
var box5;
var box6;
var box7;
var box8;
var box9;
var wins = function wins(){
	if ($("#tl1").attr("value","x")  && $("#tl2").attr("value","x") && $("#tl3").attr("value","x")|| 
		box4 === "X" && box5 === "X" && box6 === "X" || 
		box7 === "X" && box8 === "X" && box9 === "X" ||
		box1 === "X" && box4 === "X" && box7 === "X" ||
		box2 === "X" && box5 === "X" && box8 === "X" ||
		box3 === "X" && box6 === "X" && box9 === "X" ||
		box1 === "X" && box5 === "X" && box9 === "X" ||
		box3 === "X" && box5 === "X" && box7 === "X")
		{letPlay;
		alert ("player X won");
		console.log("X wins");}

// }

	 else if (box1 === "O" && box2 === "O" && box3 === "O"|| 
		box4 === "O" && box5 === "O" && box6 === "O"|| 
		box7 === "O" && box8 === "O" && box9 === "O"||
		box1 === "O" && box4 === "O" && box7 === "O"||
		box2 === "O" && box5 === "O" && box8 === "O"||
		box3 === "O" && box6 === "O" && box9 === "O"||
		box1 === "O" && box5 === "O" && box9 === "O"||
		box3 === "O" && box5 === "O" && box7 === "O")
			{alert ("player X won");
			letPlay;
			console.log("O wins ");}
}

$("#tl1").click(function(){
	if(counter % 2 === 0){
		$("#tl1").css('background-image' , 'url(https://upload.wikimedia.org/wikipedia/commons/f/f8/X_G.png)' );
		$("#tl1").attr("value","x");
		var box1 = "X";
		counter++;
		
		} else {
		$("#tl1").css('background-image' , 'url(http://www.ourdesigns.com/sites/odi/images/big/REX00NB20_big.jpg)' );
	//$('#tl1').id("x");
        $("#tl1").attr("value","o");
        var box1 = "O";
		counter++;
		

	}
		// xWins();
		// yWins();

**Comment by andrewfritz86** [comment]
Did you push your latest code to origin master?
